name: ropstam_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/images/
